### ISSUE TITLE
Multiple line breaks don't work

### ISSUE THREAD

**Issue by p3t3r67x0** [6etacat/vue-markdown-plus#1]
When I try to insert multiple line breaks or in other words a line break followed by an other line break does not work. Any idea what could be done?

```md
Hello World


Foobar
```

**Comment by michaelmyc** [comment]
In markdown, you use a trailing "\\" or trailing double space to line break. Empty lines (one or many) signifies new paragraph. A line break (html `<br>`) is different from a new paragraph (html `<p>paragraph</p>`). 

```
This is an example\
for line break with "\\"

This is another example  
for line break with "  "

You can add an empty paragraph

&nbsp;

with "\&nbsp;", which is a special space character. 
```

This is how the previous example would render:

This is an example\
for line break with "\\"

This is another example  
for line break with "  "

You can add an empty paragraph

&nbsp;

with "\&nbsp;", which is a special space character.
