### ISSUE TITLE
Tags 'code'

### ISSUE THREAD

**Issue by wgjr** [6etacat/vue-markdown-plus#2]
Good morning, thanks for the excellent support class.

"code" tags are not interpreted correctly.

They do not receive the layout correctly. Do we have any way to force them?

import VueMarkdownPlus from 'vue-markdown-plus';
   components: {
     VueMarkdownPlus,
   },

         <vue-markdown-plus: source = "content.Text"> </vue-markdown-plus>

**Comment by michaelmyc** [comment]
Can you provide more information about your issues? What do you mean by "not interpreted correctly" and "receive the layout correctly"?

**Comment by michaelmyc** [comment]
Closed due to inactivity.
