### ISSUE TITLE
Allow TOC to render with nav/nav-item to support scrollspy

### ISSUE THREAD

**Issue by pcmacdon** [6etacat/vue-markdown-plus#3]
First thanks for updating this package: I find it very useful.

A cool feature to have though would be ability to support scrollspy by using b-nav/b-nav-item instead of ul/li.

Not sure how to go about it myself.

**Comment by michaelmyc** [comment]
This is likely not possible. The b-nav component is a bootstrap-vue component, which is not supported by regular HTML. The package compiles markdown into HTML and injects it into a div so the user would see the content in the browser. This does not transpile markdown into Vue, so what you are looking for is not feasible. 

What you are looking for is a markdown to Vue transpiler that compiles markdown into Vue snippets that you can then insert into your Vue source code.

**Comment by pcmacdon** [comment]
Yes, after adding nav/nav-item classes dynamically to try and get scrollspy  working,
 I realize that instead I'll have to write a Vue component to build the TOC dynamically.
