### ISSUE TITLE
Error in vue-markdown-plus.common.js

### ISSUE THREAD

**Issue by binotaliu** [6etacat/vue-markdown-plus#5]
This file: https://github.com/6etacat/vue-markdown-plus/blob/master/dist/vue-markdown-plus.common.js
contains error:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/67255597/90202734-1537a500-de11-11ea-984c-0bee45512e1e.png">

**Comment by michaelmyc** [comment]
Posting a picture of an excerpt of the code doesn't help me with pinpointing the issue. Let me know how I can reproduce the issue or I can't help.

**Comment by binotaliu** [comment]
Using ES6 import in vue single file component file:
```vue
import VueMarkdownPlus from 'vue-markdown-plus'
```
Then compile using webpack.

The code in the screenshot shows that `punycode` isn't bundled correctly. Codes in `eval` can't be run inside browser.

**Comment by michaelmyc** [comment]
The newest version should solve this issue.
