### ISSUE TITLE
It seems that there is no function to upload pictures

### ISSUE THREAD

**Issue by itDjango** [6etacat/vue-markdown-plus#7]
Thank you
Compared with vue-markdown, it solves the xss problem very well，awesome.
However, for a Markdown, the functions seem to be a bit small, 
such as image upload and other commonly used Markdown syntax

**Comment by michaelmyc** [comment]
Hi, thank you for your suggestions. Currently, I'm pretty busy and not actively maintaining the project. I'm looking to add compatibility with Vue 3 (if it doesn't work now) once I'm less busy. 

This library only renders Markdown and is not a Markdown editor, thus image upload will not be supported in this package. Not all uses of this package will want a fully-fledged Markdown editor, and it's good to keep packages small. 

You may want to create a wrapper component around this to add functionality. I can definitely create one when I'm not busy, but that will be a low priority for me. If you create one, please let me know. I will update my descriptions to point people to your package if they need an editor component.

**Comment by itDjango** [comment]
thank you~

**Comment by AxelBriche** [comment]
Hello. Have you a suggestion of a Markdown editor easy to extend please?

**Comment by michaelmyc** [comment]
@AxelBriche I'm not aware of anything popular. You can try building one yourself. I feel like a plain text markdown input is more than sufficient. If you're trying to build a comments section, it's best to consider services like discuz, or use github as a host with tools like utterances.
